name: JustLayMe
options:
  bundleIdPrefix: com.justlayme
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  developmentLanguage: en

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    ENABLE_PREVIEWS: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
    CODE_SIGN_STYLE: Automatic
    PRODUCT_BUNDLE_IDENTIFIER: com.justlayme.app

  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: "-O"

targets:
  JustLayMe:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App
      - path: Core
      - path: Models
      - path: Services
      - path: ViewModels
      - path: Views
      - path: Resources
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleDisplayName: JustLayMe
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.social-networking"
        INFOPLIST_KEY_NSCameraUsageDescription: "Allow camera access for profile photos"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Allow photo library access for profile photos"
        INFOPLIST_KEY_NSFaceIDUsageDescription: "Use Face ID for secure login"
      configs:
        Debug:
          PRODUCT_NAME: "JustLayMe Dev"
        Release:
          PRODUCT_NAME: JustLayMe
    dependencies:
      - package: Alamofire
      - package: Nuke
      - package: KeychainSwift
      - package: Starscream
    entitlements:
      path: Resources/JustLayMe.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        aps-environment: development

  JustLayMeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: JustLayMe
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/JustLayMe.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/JustLayMe"

  JustLayMeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - UITests
    dependencies:
      - target: JustLayMe
    settings:
      base:
        TEST_TARGET_NAME: JustLayMe

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: "5.8.0"
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: "12.0.0"
  KeychainSwift:
    url: https://github.com/evgenyneu/keychain-swift.git
    from: "20.0.0"
  Starscream:
    url: https://github.com/daltoniam/Starscream.git
    from: "4.0.0"

schemes:
  JustLayMe:
    build:
      targets:
        JustLayMe: all
        JustLayMeTests: [test]
        JustLayMeUITests: [test]
    run:
      config: Debug
      environmentVariables:
        - variable: IDEPreferLogStreaming
          value: "YES"
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - JustLayMeTests
        - JustLayMeUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
